---
- hosts: all
  become: yes
  tasks:
     - name: Install apche2
       apt:
         name: apache2
         state: absent
     - name: Install tree
       apt:
         name: tree
         state: absent
