---
- hosts: all
  become: yes
  tasks:
     - name: Install apche2
       apt:
         name: apache2
         state: present
     - name: Install httpd
       apt:
         name: httpd
         state: present
