---
- hosts: mywebservers
  become: yes
  tasks:
     - name: Install apche2
       apt:
         name: "{{installapche2ondebian}}"
         state: present
       when: ansible_os_family=="Debian"
     - name: start apache2
       service:
         name: "{{installapche2ondebian}}"
         state: started
       when: ansible_os_family=="Debian"
     - name: Install httpd
       yum:
         name: "{{installhttpdonredhat}}"
         state: present
       when: ansible_os_family=="RedHat"
     - name: start httpd
       service:
         name: "{{installhttpdonredhat}}"
         state: started
       when: ansible_os_family=="RedHat"